Algoritmo "areadoretangulo "
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : caulcular a area do retangulo
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
comprimento,largura,area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("comprimento")
leia(comprimento)
escreva("largura")
leia(largura)
area<-comprimento*largura
escreva(area)


Fimalgoritmo