Algoritmo "areatrapezio "
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Calcular area de um trapezio
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
BM,b,h,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("BM")
leia(BM)
escreva("b")
leia(b)
escreva("h")
leia(h)
area<-(BM+b)*h/2
escreva(area)


Fimalgoritmo