Algoritmo "medianotas "
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Calcular a media das notas dos alunos
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
x,y,z,m:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("x")
leia(x)
escreva("y")
leia(y)
escreva("z")
leia(z)
m<-(x+y+z)/3
escreva(m)


Fimalgoritmo