Algoritmo "perimetrocircunferncia "
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Calcular perimetro de uma circunferencia
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
r,p:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("r")
leia(r)
p<-2*3.1415*r
escreva(p)


Fimalgoritmo