Algoritmo "salarionovo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Calcular o salario novo
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
sa,a,sn:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("sa")
leia(sa)
escreva("a")
leia(a)
escreva("sn")
leia(sn)
sn<-(sa*a/100)+sa
escreva(sn)


Fimalgoritmo