Algoritmo "volumeparalelipipedo "
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Calcular volume de um paralelipipedo
// Autor(a)    : João Martins
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
l,c,h,volume:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("l")
leia(l)
escreva("c")
leia(c)
escreva("h")
leia(h)
volume<-l*c*h
escreva(volume)


Fimalgoritmo